#!/usr/bin/env python3.7

import os
import requests
import sys
import json
import pytemperature

from argparse import ArgumentParser

parser = ArgumentParser(description='Get the current weather information for your city')
parser.add_argument('city', help='city to get weather for')
parser.add_argument('--country', default='us', help='country city belongs to, default is "us"')

args = parser.parse_args()

api_key = os.getenv("OWM_API_KEY")

if not api_key:
    print("Error: No 'OWM_API_KEY' provided")
    sys.exit(1)

url = f"http://api.openweathermap.org/data/2.5/weather?q={args.city},{args.country}&appid={api_key}"

res = requests.get(url)
##print(res)

if res.status_code != 200:
    print(f"Error talking to weather provider: {res.status_code}")
    sys.exit(1)

##print(res.json())

result = res.json()

y = result['main']
current_temperature = y["temp"]
current_pressure = y["pressure"]
current_humidity = y["humidity"]
z = result["weather"]
weather_description = z[0]["description"]

print(" Temperature (in Kelvin) = " +
        str(current_temperature) +
        "\n Temperature (in Celsius) = " +
        str(pytemperature.k2c(current_temperature)) +
        "\n Temperature (in Farenheit) = " +
        str(pytemperature.k2f(current_temperature)) +
        "\n Atmospheric pressure (in hPa unit) = " +
        str(current_pressure) +
        "\n Humidity (in percentage) = " +
        str(current_humidity) +
        "\n Description = " +
        str(weather_description))
